//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue May 28 14:52:26 2024 by ROOT version 6.30/02)
//      from the StreamerInfo in file out/coverage.root
//////////////////////////////////////////////////////////


#ifndef BinSet_h
#define BinSet_h
class BinSet;

#include "Rtypes.h"
#include "TObject.h"
#include "TObjArray.h"
#include <TString.h>

class BinSet : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TObjArray*  binList;     //array of `CutDef*`s
   TString     varName;     //
   TString     varTitle;    //

   BinSet();
   BinSet(BinSet && ) = default;
   BinSet &operator=(const BinSet & );
   BinSet(const BinSet & );
   virtual ~BinSet();

   ClassDef(BinSet,2); // Generated by MakeProject.
};
#endif
