//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue May 28 14:52:26 2024 by ROOT version 6.30/02)
//      from the StreamerInfo in file out/coverage.root
//////////////////////////////////////////////////////////


#ifndef HistConfig_h
#define HistConfig_h
class HistConfig;

#include "Rtypes.h"
#include "TNamed.h"

class HistConfig : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        logx;        //
   bool        logy;        //
   bool        logz;        //
   bool        logw;        //

   HistConfig();
   HistConfig(HistConfig && ) = default;
   HistConfig &operator=(const HistConfig & );
   HistConfig(const HistConfig & );
   virtual ~HistConfig();

   ClassDef(HistConfig,2); // Generated by MakeProject.
};
#endif
