//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue May 28 14:52:26 2024 by ROOT version 6.30/02)
//      from the StreamerInfo in file out/coverage.root
//////////////////////////////////////////////////////////


#ifndef Hist4D_h
#define Hist4D_h
class Hist4D;

#include "Rtypes.h"
#include "TNamed.h"
#include "TAxis.h"
#include "TH2.h"
#include "Riostream.h"
#include <vector>

class Hist4D : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   TAxis*      _w_axis;     //
   TAxis*      _x_axis;     //
   TAxis*      _y_axis;     //
   TAxis*      _z_axis;     //
   TH2D*       _axes;       //
   vector<TH2D*> _hists;      //
   double        _minimum;    //
   double        _maximum;    //

   Hist4D();
   Hist4D(Hist4D && ) = default;
   Hist4D &operator=(const Hist4D & );
   Hist4D(const Hist4D & );
   virtual ~Hist4D();

   ClassDef(Hist4D,2); // Generated by MakeProject.
};
#endif
